module.exports = {
    config: {
        name: "trade",
        version: "4.0.0",
        author: "Xdragon",
        role: 0,
        description: "English Web-Integrated Trade & Midman Portal Controlled via Messenger Hub",
        category: "system",
        aliases: ["web", "show"]
    },

    onStart: async function ({ api, event, args }) {
        const adminUID = "61583174657283";
        const fs = require('fs-extra');
        const path = require('path');
        const dataPath = path.join(__dirname, "trade_data.json");

        // Initialize Database Setup
        if (!fs.existsSync(dataPath)) {
            fs.writeFileSync(dataPath, JSON.stringify({ verified: [], midmen: [], midman_inbox: [], tokens: {}, trades: [], user_inboxes: {} }, null, 2));
        }

        // --- WEB SERVER INTEGRATION ---
        if (!global.tradeServerRunning) {
            const express = require('express');
            const app = express();
            const port = process.env.PORT || 3000;

            app.use(express.json());
            app.use(express.urlencoded({ extended: true }));

            const readData = () => JSON.parse(fs.readFileSync(dataPath));
            const writeData = (d) => fs.writeFileSync(dataPath, JSON.stringify(d, null, 2));

            // Home Route
            app.get('/', (req, res) => {
                res.send(getHTMLTemplate("Portal Home", `
                    <div class="text-center py-8">
                        <img src="https://cdn-icons-png.flaticon.com/512/10061/10061834.png" class="w-24 h-24 mx-auto mb-4 rounded-full shadow-lg">
                        <h1 class="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Xdragon Trading & Midman Hub</h1>
                        <p class="mt-4 text-lg text-slate-300 max-w-xl mx-auto">The official portal for secure transactions, anti-scam web verification, and midman applications.</p>
                        
                        <div class="mt-8 bg-slate-800/80 border border-slate-700 rounded-xl p-6 text-left shadow-xl">
                            <h3 class="text-xl font-bold text-teal-400 mb-3">📢 How to Access Your Dashboard</h3>
                            <ol class="list-decimal list-inside space-y-2 text-slate-300">
                                <li>Go to Messenger and message the bot: <code class="bg-slate-900 px-2 py-0.5 text-yellow-400 rounded">~trade verify</code></li>
                                <li>Click the secure link generated by the bot to synchronize your profile session securely.</li>
                            </ol>
                        </div>
                    </div>
                `));
            });

            // Dashboard Portal Route
            app.get('/portal', async (req, res) => {
                const { token } = req.query;
                const db = readData();
                if (!token || !db.tokens[token]) return res.send(getHTMLTemplate("Session Error", "<p class='text-red-400 text-center text-xl font-bold'>❌ Invalid or Expired Session Token. Please request a new link using ~trade verify</p>"));

                const user = db.tokens[token];
                let userInfo = { name: "Trader User", profileUrl: "https://cdn-icons-png.flaticon.com/512/149/149071.png" };
                try {
                    const info = await api.getUserInfo(user.uid);
                    if (info && info[user.uid]) {
                        userInfo.name = info[user.uid].name;
                        userInfo.profileUrl = info[user.uid].thumbSrc || userInfo.profileUrl;
                    }
                } catch(e){}

                const isTrader = db.verified.includes(user.uid) ? '🟢 Verified Trader' : '🔴 Unverified Member';
                const isMidman = db.midmen.includes(user.uid) ? '💎 Official Midman' : '⚪ Standard Member';
                const userNotifications = db.user_inboxes[user.uid] || [];

                res.send(getHTMLTemplate("Dashboard", `
                    <div class="flex items-center space-x-4 p-4 bg-slate-800 border border-slate-700 rounded-xl mb-6">
                        <img src="${userInfo.profileUrl}" class="w-16 h-16 rounded-full border-2 border-teal-400">
                        <div>
                            <h2 class="text-2xl font-bold text-white">${userInfo.name}</h2>
                            <p class="text-sm text-slate-400">UID: ${user.uid}</p>
                            <div class="flex space-x-2 mt-1">
                                <span class="text-xs px-2 py-0.5 bg-slate-900 rounded text-teal-300 font-semibold">${isTrader}</span>
                                <span class="text-xs px-2 py-0.5 bg-slate-900 rounded text-purple-300 font-semibold">${isMidman}</span>
                            </div>
                        </div>
                    </div>

                    <!-- Verification Modules -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                        <div class="bg-slate-800/60 border border-slate-700 rounded-xl p-5 shadow-lg hover:border-teal-500 transition-all">
                            <h3 class="text-lg font-bold text-teal-400 mb-2">🛡️ Trader Verification Portal</h3>
                            <p class="text-sm text-slate-300 mb-4">Complete our 10-item anti-scam questionnaire. Required passing score: 6/10.</p>
                            <a href="/quiz-trader?token=${token}" class="inline-block w-full text-center py-2 bg-teal-500 text-slate-900 font-bold rounded-lg transition-colors">Start Web Verification</a>
                        </div>
                        <div class="bg-slate-800/60 border border-slate-700 rounded-xl p-5 shadow-lg hover:border-purple-500 transition-all">
                            <h3 class="text-lg font-bold text-purple-400 mb-2">💎 Midman License Exam</h3>
                            <p class="text-sm text-slate-300 mb-4">Apply as an official trusted intermediary. Heavy scenario testing. Passing Score: 15/20.</p>
                            <a href="/quiz-midman?token=${token}" class="inline-block w-full text-center py-2 bg-purple-500 text-white font-bold rounded-lg transition-colors">Take Licensure Exam</a>
                        </div>
                    </div>

                    <!-- Personal Notification Inbox -->
                    <div class="bg-slate-800 border border-slate-700 rounded-xl p-5 mb-8">
                        <h3 class="text-xl font-bold text-teal-400 mb-4">📥 Your Personal Inbox Notifications (~trade request)</h3>
                        <div class="space-y-2">
                            ${userNotifications.length === 0 ? '<p class="text-sm text-slate-500 italic">No incoming notifications or active updates found.</p>' : 
                                userNotifications.reverse().map(note => `<div class="p-3 bg-slate-900/60 border border-slate-700/50 rounded-lg text-sm"><span class="text-slate-400 font-mono text-xs block">${note.time}</span>${note.msg}</div>`).join('')
                            }
                        </div>
                    </div>

                    <!-- Public Marketplace List -->
                    <div class="bg-slate-800 border border-slate-700 rounded-xl p-5 mb-8">
                        <h3 class="text-xl font-bold text-blue-400 mb-4">📦 Live Marketplace Directory</h3>
                        <div class="overflow-x-auto">
                            <table class="w-full text-left text-sm divide-y divide-slate-700">
                                <thead><tr class="text-slate-400"><th>Item Name</th><th>Stocks</th><th>Price</th><th>Trade ID</th></tr></thead>
                                <tbody class="divide-y divide-slate-800">
                                    ${db.trades.length === 0 ? '<tr><td colspan="4" class="p-4 text-center text-slate-500">No marketplace listings available. Add via ~trade command.</td></tr>' : 
                                        db.trades.map(t => `<tr><td class="p-2 font-bold text-white">${t.itemName}</td><td class="p-2">${t.stocks}</td><td class="p-2 text-yellow-400 font-bold">${t.price}</td><td class="p-2 font-mono text-xs text-blue-300">${t.tradeId}</td></tr>`).join('')
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- Live Midman Monitor Request Control -->
                    ${db.midmen.includes(user.uid) || user.uid === adminUID ? `
                        <div class="bg-slate-800 border border-slate-700 rounded-xl p-5">
                            <h3 class="text-xl font-bold text-yellow-400 mb-4">📥 Live Midman Request Inbox (~midman calls)</h3>
                            <div class="overflow-x-auto">
                                <table class="w-full text-left text-sm divide-y divide-slate-700">
                                    <thead><tr class="text-slate-400"><th>Timestamp</th><th>Caller</th><th>Tagged Midman</th><th>Thread Link/ID</th></tr></thead>
                                    <tbody class="divide-y divide-slate-800 text-slate-300">
                                        ${db.midman_inbox.length === 0 ? '<tr><td colspan="4" class="p-4 text-center text-slate-500">No pending active midman queue logs.</td></tr>' : 
                                            db.midman_inbox.reverse().map(item => `<tr><td class="p-2 text-slate-400">${item.time}</td><td class="p-2 font-semibold text-white">${item.sender}</td><td class="p-2 text-yellow-300">${item.mentioned}</td><td class="p-2 text-teal-400 font-mono text-xs">${item.thread}</td></tr>`).join('')
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    ` : ''}
                `));
            });

            // TRADER QUIZ VIEW
            app.get('/quiz-trader', (req, res) => {
                const { token } = req.query;
                res.send(getHTMLTemplate("Trader Verification", `
                    <h2 class="text-2xl font-bold text-teal-400 mb-2">📝 Anti-Scam Questionnaire (10 Items)</h2>
                    <form action="/submit-trader?token=${token}" method="POST" class="space-y-4 mt-4">
                        ${getTraderQuestions().map((q, idx) => `
                            <div class="bg-slate-800 p-4 border border-slate-700 rounded-lg">
                                <p class="font-medium mb-2">${idx + 1}. ${q}</p>
                                <label class="mr-4"><input type="radio" name="q${idx}" value="yes" required class="text-teal-500"> Yes</label>
                                <label><input type="radio" name="q${idx}" value="no" required class="text-teal-500"> No</label>
                            </div>
                        `).join('')}
                        <button type="submit" class="w-full bg-teal-500 text-slate-900 font-bold py-3 rounded-xl transition-all shadow-lg text-lg">Submit Verification Answers</button>
                    </form>
                `));
            });

            // PROCESS TRADER SUBMISSION
            app.post('/submit-trader', (req, res) => {
                const { token } = req.query;
                const db = readData();
                if (!token || !db.tokens[token]) return res.send("Token Expired.");
                const uid = db.tokens[token].uid;
                const expected = ["yes", "no", "yes", "yes", "yes", "yes", "no", "yes", "yes", "yes"];
                let score = 0;
                for (let i = 0; i < 10; i++) if (req.body[`q${i}`] === expected[i]) score++;

                if (score >= 6) {
                    if (!db.verified.includes(uid)) db.verified.push(uid);
                    writeData(db);
                    api.sendMessage(`🎉 Web Update: You successfully passed the Website Trader Verification with a score of ${score}/10!`, uid);
                    res.send(getHTMLTemplate("Passed", `<div class="text-center py-6"><h2 class="text-3xl font-extrabold text-teal-400 mb-2">🎉 Verification Passed!</h2><p class="text-slate-300">Your score: <strong>${score}/10</strong></p><p class="mt-4"><a href="https://m.me/j/AbYAGP_SaggwbsWy/" target="_blank" class="text-yellow-400 font-bold underline text-lg">Click to Access Main Trading Area</a></p><p class="mt-6"><a href="/portal?token=${token}" class="text-slate-400 underline text-sm">Return to Dashboard</a></p></div>`));
                } else {
                    res.send(getHTMLTemplate("Failed", `<div class="text-center py-6"><h2 class="text-3xl font-extrabold text-red-400 mb-2">🚨 Verification Failed</h2><p class="text-slate-300">Your score was ${score}/10. You need at least 6/10 to pass.</p><a href="/portal?token=${token}" class="mt-6 inline-block bg-slate-700 text-white px-4 py-2 rounded-lg">Back to Dashboard</a></div>`));
                }
            });

            // MIDMAN QUIZ VIEW
            app.get('/quiz-midman', (req, res) => {
                const { token } = req.query;
                res.send(getHTMLTemplate("Midman Application", `
                    <h2 class="text-2xl font-bold text-purple-400 mb-2">💎 Midman Certification Exam (20 Items)</h2>
                    <form action="/submit-midman?token=${token}" method="POST" class="space-y-4 mt-4">
                        ${getMidmanQuestions().map((q, idx) => `
                            <div class="bg-slate-800 p-4 border border-slate-700 rounded-lg">
                                <p class="font-medium mb-2">${idx + 1}. ${q.text}</p>
                                <label class="block mb-1"><input type="radio" name="m${idx}" value="A" required class="text-purple-500"> A) ${q.a}</label>
                                <label class="block"><input type="radio" name="m${idx}" value="B" required class="text-purple-500"> B) ${q.b}</label>
                            </div>
                        `).join('')}
                        <button type="submit" class="w-full bg-purple-500 text-white font-bold py-3 rounded-xl shadow-lg text-lg">Submit Midman Examination</button>
                    </form>
                `));
            });

            // PROCESS MIDMAN SUBMISSION
            app.post('/submit-midman', (req, res) => {
                const { token } = req.query;
                const db = readData();
                if (!token || !db.tokens[token]) return res.send("Token Expired.");
                const uid = db.tokens[token].uid;
                const expected = ["A", "A", "B", "A", "A", "B", "A", "B", "A", "A", "B", "A", "A", "B", "A", "A", "B", "A", "B", "A"];
                let score = 0;
                for (let i = 0; i < 20; i++) if (req.body[`m${i}`] === expected[i]) score++;

                if (score >= 15) {
                    if (!db.midmen.includes(uid)) db.midmen.push(uid);
                    writeData(db);
                    api.sendMessage(`💎 Certification Result: PASSED! You are now an official registered Midman with a score of ${score}/20!`, uid);
                    res.send(getHTMLTemplate("Passed Midman", `<div class="text-center py-6"><h2 class="text-3xl font-extrabold text-purple-400 mb-2">🎉 Application Approved!</h2><p class="text-slate-300">Score: <strong>${score}/20</strong>. You now have full dashboard access to handle live middleman alerts.</p><a href="/portal?token=${token}" class="mt-6 inline-block bg-purple-600 px-4 py-2 text-white rounded-lg">Go to Dashboard</a></div>`));
                } else {
                    res.send(getHTMLTemplate("Failed Midman", `<div class="text-center py-6"><h2 class="text-3xl font-extrabold text-red-400 mb-2">🚨 Exam Failed</h2><p class="text-slate-300">You scored ${score}/20. The safety threshold requires a minimum score of 15/20.</p><a href="/portal?token=${token}" class="mt-6 inline-block bg-slate-700 px-4 py-2 text-white rounded-lg">Back and Review</a></div>`));
                }
            });

            app.listen(port, () => console.log(`[TRADE SYSTEM] Server running on port ${port}`));
            global.tradeServerRunning = true;
        }
    },

    onChat: async function ({ api, event }) {
        if (!event.body) return;

        const fs = require('fs-extra');
        const path = require('path');
        const crypto = require('crypto');
        const dataPath = path.join(__dirname, "trade_data.json");

        if (!fs.existsSync(dataPath)) return;
        const db = JSON.parse(fs.readFileSync(dataPath));
        const senderIDStr = String(event.senderID);
        const msgText = event.body.trim();

        const options = { timeZone: "Asia/Manila", hour12: true, hour: "2-digit", minute: "2-digit" };
        const stamp = new Date().toLocaleTimeString("en-US", options);

        // --- COMMAND 1: ~trade verify (Generates Link Access to Web Verification Dashboard) ---
        if (msgText.toLowerCase() === "~trade verify") {
            const token = crypto.randomBytes(8).toString('hex');
            if (!db.tokens) db.tokens = {};
            db.tokens[token] = { uid: senderIDStr, generatedAt: Date.now() };
            fs.writeFileSync(dataPath, JSON.stringify(db, null, 2));

            const localUrl = `http://localhost:3000/portal?token=${token}`; // Replace with domain when deployed
            return api.sendMessage(`🔑 **SECURE VERIFICATION ACCESSPORT** 🔑\n\nClick the link below to verify your account credentials or apply for midman duties safely on our web configuration panel:\n\n🔗 ${localUrl}\n\n*(Keep this link private. It acts as your dynamic auto-login access code).*`, event.threadID, event.messageID);
        }

        // --- COMMAND 2: ~midman @mention (Triggers real-time midman alerts to web engine logs) ---
        if (msgText.toLowerCase().startsWith("~midman") && event.mentions) {
            const mentionUIDs = Object.keys(event.mentions);
            if (mentionUIDs.length > 0) {
                let senderName = "Unknown Trader";
                try {
                    const uInfo = await api.getUserInfo(senderIDStr);
                    if (uInfo && uInfo[senderIDStr]) senderName = uInfo[senderIDStr].name;
                } catch(e){}

                const mentionedName = event.mentions[mentionUIDs[0]].replace("@", "");
                if (!db.midman_inbox) db.midman_inbox = [];
                db.midman_inbox.push({ time: stamp, sender: senderName, mentioned: mentionedName, thread: String(event.threadID) });
                
                fs.writeFileSync(dataPath, JSON.stringify(db, null, 2));
                return api.sendMessage(`🔔 System Notification: Your middleman request for ${mentionedName} has been successfully dispatched to the Active Web Inbox Hub.`, event.threadID, event.messageID);
            }
        }

        // --- COMMAND 3: ~trade request (Pings user back & adds system logs inside the Web UI inbox) ---
        if (msgText.toLowerCase() === "~trade request") {
            if (!db.user_inboxes) db.user_inboxes = {};
            if (!db.user_inboxes[senderIDStr]) db.user_inboxes[senderIDStr] = [];

            const notificationMessage = `Your trade request trigger successfully synced with the live portal database logs on ${stamp}.`;
            db.user_inboxes[senderIDStr].push({ time: stamp, msg: notificationMessage });
            
            fs.writeFileSync(dataPath, JSON.stringify(db, null, 2));
            return api.sendMessage(`📩 **Request Processed**\n\nYour alert check trace has been successfully sent back! Check your personal Web Dashboard Inbox for complete transaction breakdowns.`, event.threadID, event.messageID);
        }

        // --- COMMAND 4: ~trade {item name} {stocks} {price} {Id} (Logs and posts live trade metrics) ---
        if (msgText.toLowerCase().startsWith("~trade ") && msgText.toLowerCase() !== "~trade verify" && msgText.toLowerCase() !== "~trade request") {
            // Regex parsing format: ~trade [Item Name with spaces] [Stocks Content] [Price Value] [Unique Id String]
            const tradeRegex = /^~trade\s+(.+)\s+(\S+)\s+(\S+)\s+(\S+)$/i;
            const match = msgText.match(tradeRegex);

            if (!match) {
                return api.sendMessage(`⚠️ **Invalid Listing Structure**\n\nPlease construct your asset command accurately:\nFormat: \`~trade {item name} {stocks} {price} {Id}\`\nExample: \`~trade Dragon Sword 5 1500cr DS-99X\``, event.threadID, event.messageID);
            }

            const [_, itemName, stocks, price, tradeId] = match;
            if (!db.trades) db.trades = [];
            db.trades.push({ itemName, stocks, price, tradeId, sellerUID: senderIDStr, time: stamp });
            
            fs.writeFileSync(dataPath, JSON.stringify(db, null, 2));
            return api.sendMessage(`📦 **MARKETPLACE POSTING COMPLETED**\n\nYour trade offering has been indexed onto the web system:\n🔹 Item: ${itemName}\n🔹 Inventory Count: ${stocks}\n🔹 Value: ${price}\n🔹 Identifier Code: ${tradeId}`, event.threadID, event.messageID);
        }
    }
};

// --- REUSABLE MASTER WEB UI LAYOUT TEMPLATE ---
function getHTMLTemplate(title, bodyContent) {
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">
        <style>body { font-family: 'Plus Jakarta Sans', sans-serif; }</style>
    </head>
    <body class="bg-gradient-to-tr from-slate-950 via-slate-900 to-slate-950 min-h-screen text-slate-100 flex flex-col justify-between">
        <header class="border-b border-slate-800 bg-slate-950/40 backdrop-blur-md sticky top-0 z-50">
            <div class="max-w-4xl mx-auto px-4 py-4 flex justify-between items-center">
                <span class="text-xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-purple-400">🛡️ Xdragon Verification Web Engine</span>
                <span class="text-xs bg-slate-800 text-slate-400 px-3 py-1 rounded-full font-mono">v4.0.0 Global UI</span>
            </div>
        </header>
        <main class="max-w-4xl w-full mx-auto px-4 py-8 flex-grow">${bodyContent}</main>
        <footer class="border-t border-slate-900 bg-slate-950/20 text-center py-4 text-xs text-slate-600">
            &copy; 2026 Xdragon Development System. Secured Web Terminal.
        </footer>
    </body>
    </html>`;
}

function getTraderQuestions() {
    return [
        "Do you completely agree to comply with all specific corporate platform trading parameters?",
        "Have you ever been verified or accused as an operational scammer within peer communities?",
        "Do you agree to use an Authorized System Midman for every single trading deal?",
        "Is the current messenger profile account you are utilizing your primary active main account?",
        "Do you accept an immediate permanent administrative ban if you are caught executing fraudulent work?",
        "Will you supply complete unedited evidence or structural proof before finalizing item exchanges?",
        "Have you ever been blacklisted or banned across secondary trading communities in the past?",
        "Will you preserve complete communication respect between buyers and sellers at all costs?",
        "Will you unconditionally decline unverified external configuration or validation links from other parties?",
        "Are you using this hub solely for honest, legit, and high-integrity transactional trades?"
    ];
}

function getMidmanQuestions() {
    return [
        { text: "What is the primary operational obligation of a Midman before processing a deal transaction?", a: "Verify the legal profile ownership, identity, and background parameters of both interacting parties.", b: "Immediately demand full item values and currency deposits without evaluation questions." },
        { text: "A user submits a transaction billing proof image that appears potentially modified. What is your response?", a: "Halt processing and manually double-check corporate bank dashboards to ensure balance clearance.", b: "Trust the visual screenshot and immediately release the account assets." },
        { text: "Who must retain full administrative custody of trade assets while exchanges are being finalized?", a: "The prospective primary seller.", b: "The officially assigned secure system Midman." },
        { text: "Are you ever allowed to distribute trade account ownership access data prior to direct confirmation from the buyer?", a: "Absolutely never under any circumstances.", b: "Yes, if either user states they are running out of schedule time." },
        { text: "An interacting user suddenly attempts to transfer transactional interactions outside the secure portal. What is your action?", a: "Politely decline and cancel the immediate trade to preserve system safety standards.", b: "Follow their guidance to wrap the process up quickly." },
        { text: "Must a licensed Midman remain perfectly neutral when a transactional dispute arises?", a: "No, you must back up the user you are personally familiar with.", b: "Yes, make structural decisions based strictly on tangible evidence." },
        { text: "A user sends a data link asking you to verify account info on an external engine. Do you click it?", a: "No, this is highly likely a malicious credential phishing attempt.", b: "Yes, to speed up checking phases." },
        { text: "Which of the following traits strongly exposes a potential malicious scam behavior?", a: "Using an older, authenticated, highly active main profile framework.", b: "Exerting extreme time pressure and consistently avoiding official hub processes." },
        { text: "Once an exchange settles successfully, what is your closing step as an active Midman?", a: "Capture comprehensive final visual execution logs and update system database statuses.", b: "Block both profiles immediately to save processing space." },
        { text: "How should long-term transaction and chat history verification logs be handled by staff?", a: "Preserved carefully within isolated storage setups to back up potential future claims.", b: "Deleted instantly to avoid data collection." },
        { text: "Who holds the final administrative authority to declare an active exchange block fully complete?", a: "The buyer exclusively.", b: "The active Midman after validating successful asset transfers on both ends." },
        { text: "Is it safe to middleman high-value trades exclusively via voice call recordings without written data records?", a: "No, because structured proof lines become highly hard to track accurately.", b: "Yes, voice call confirmation is faster." },
        { text: "How do you handle a scenario where an active trade user begins threatening you during operational duties?", a: "Log the records to Admin staff, pause transaction processing, and lock asset pools.", b: "Give them whatever information or data asset they want to de-escalate." },
        { text: "Are you permitted to temporarily use or lease game profiles or currency held within system escrow custody?", a: "Yes, provided the users give you informal chat permission.", b: "No, this is strictly illegal and triggers instant license terminations." },
        { text: "How do you definitively prove to users that you are the authentic system profile and not a duplicate clone?", a: "Direct them to confirm your active data profile directly through the official website web portal dashboard.", b: "Send text messages telling them to just rely on faith." },
        { text: "What is the appropriate protocol if a banking chargeback occurs on a monetary asset in escrow?", a: "Hold the traded merchandise items and completely refuse delivery until financial remediation resolves.", b: "Go ahead and deliver the items regardless." },
        { text: "Are you allowed to extort or collect processing fee structures that exceed established system policies?", a: "No, consistently stick directly to standard corporate system rate metrics.", b: "Yes, if the specific trade proves hard to manage." },
        { text: "A user presents a modified or invalid identification document. What is your immediate reaction?", a: "Impose a database ban block and report the profile to administration lines.", b: "Ignore it for the time being to keep processing moving." },
        { text: "Are you authorized to share client transaction descriptions or trade specifics with unconcerned friends?", a: "Yes, discuss it freely across your private groups for fun.", b: "No, maintain strict user data confidentiality parameters at all times." },
        { text: "What represents the fundamental core objective of a certified system Midman?", a: "Guaranteeing 100% transparent, honest, and secure transactional exchanges.", b: "Maximizing the processing fee profits generated off trading parties." }
    ];
}
